In [46]:
import torch, torchvision
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 

In [47]:
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1,3,64,64)
labels = torch.rand(1,1000)

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to C:\Users\VikasKM/.cache\torch\hub\checkpoints\resnet18-5c106cde.pth
100%|██████████| 44.7M/44.7M [00:15<00:00, 3.00MB/s]


In [48]:
prediction = model(data)

In [49]:
loss = (prediction-labels).sum()
loss.backward()

In [50]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [51]:
optim.step()

In [199]:
# inputs = [temp, rainfall, humidity]
inputs = np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70],
], dtype='float32')
print(inputs)

[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]


In [200]:
# targets = [apples, oranges]
targets = np.array([
    [56,70],
    [81,101],
    [119,133],
    [22,37],
    [103,119],
], dtype='float32')
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [201]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [202]:
w = torch.randn((2,3), requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 1.6896, -0.0516,  1.2898],
        [-0.2356, -0.9686, -0.5105]], requires_grad=True)
tensor([-0.8661, -1.3995], requires_grad=True)


In [203]:
# y = w.T x + b
def model(x):
    return x @ w.T + b

In [204]:
preds = model(inputs.float())
print(preds)

tensor([[ 174.4781, -105.4465],
        [ 230.8930, -140.7488],
        [ 214.0232, -181.3012],
        [ 216.9747,  -85.9672],
        [ 201.0486, -146.3787]], grad_fn=<AddBackward0>)


In [205]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [206]:
def mse(y_targets, y_preds):
    diff = y_targets - y_preds
    sum = torch.sum(diff * diff)
    n = diff.numel()
    return sum / n


In [207]:
loss = mse(targets, preds)
loss

tensor(36671.9102, grad_fn=<DivBackward0>)

In [208]:
loss.backward()

In [209]:
print(w)
print(w.grad)

tensor([[ 1.6896, -0.0516,  1.2898],
        [-0.2356, -0.9686, -0.5105]], requires_grad=True)
tensor([[ 11441.7920,  10331.6621,   6855.3052],
        [-18600.9453, -21181.8242, -12874.3789]])


In [210]:
print(b)
print(b.grad)

tensor([-0.8661, -1.3995], requires_grad=True)
tensor([ 131.2835, -223.9685])


In [211]:
# settings the grads back to zero
# b.grad.zero_()
# w.grad.zero_()
# print(b.grad)
# print(w.grad)    

In [212]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_() 

In [213]:
print(w)
print(b)

tensor([[ 1.5752, -0.1549,  1.2212],
        [-0.0495, -0.7568, -0.3818]], requires_grad=True)
tensor([-0.8674, -1.3973], requires_grad=True)


In [214]:
preds = model(inputs)
print(preds)

loss = mse(targets, preds)
loss



tensor([[ 156.2543,  -72.1378],
        [ 207.0004,  -96.9401],
        [ 186.2470, -129.2654],
        [ 198.3237,  -53.1203],
        [ 178.4354, -104.1952]], grad_fn=<AddBackward0>)


tensor(25333.4082, grad_fn=<DivBackward0>)

## Training for Multiple Epochs

In [222]:
for i in range(100):
    preds = model(inputs)
    loss = mse(targets, preds)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-4
        b -= b.grad * 1e-4
        w.grad.zero_()
        b.grad.zero_() 

In [223]:
print(loss)

tensor(4.2962, grad_fn=<DivBackward0>)


In [224]:
print(preds)

tensor([[ 56.9102,  70.2830],
        [ 83.3178,  99.1543],
        [116.5735, 136.4436],
        [ 20.5908,  38.0665],
        [103.9647, 115.6127]], grad_fn=<AddBackward0>)


In [221]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
