In [29]:
import torch
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

In [30]:
t1 = torch.tensor(4.0)
print(t1)
print(t1.dtype)
print(t1.shape)   #check what is printed
print(t1.data)

tensor(4.)
torch.float32
torch.Size([])
tensor(4.)


In [31]:
t2 = torch.tensor([1.0,2.0,3.0])
print(t2)
print(t2.amax())
print(t2.sum())
print(t2.shape)
print(t2.mean())
print(t2.size())
print(t2.median())

tensor([1., 2., 3.])
tensor(3.)
tensor(6.)
torch.Size([3])
tensor(2.)
torch.Size([3])
tensor(2.)


In [32]:
t3 = torch.tensor([1.0,2,3,4])  # float and int mixed
print(t3)

tensor([1., 2., 3., 4.])


In [33]:
# shape mismatch
t4 = torch.tensor([
    [1,2],
    [3,4],
    [5,6,7],
])
print(t4)

ValueError: expected sequence of length 2 at dim 1 (got 3)

In [34]:
x = torch.tensor(3.)    # requires_grad argument missing, check ans
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

# y = wx +b
y = w*x + b
print(y)


tensor(17., grad_fn=<AddBackward0>)


In [35]:
# to calculate the gradients
y.backward()

In [36]:
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [37]:
x = torch.tensor(3., requires_grad=True)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

# y = wx +b
y = w*x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [38]:
y.backward()

In [39]:
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx tensor(4.)
dy/dw tensor(3.)
dy/db tensor(1.)


In [40]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [41]:
# uses the same memory
y = torch.from_numpy(x)
print(y)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [42]:
# creates a copy of the data
y = torch.tensor(x)
print(y)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [43]:
x.dtype, y.dtype

(dtype('int32'), torch.int32)

In [44]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [45]:
x = torch.tensor([1.0,2.0], requires_grad=True)
w = torch.tensor([1.0,2.0], requires_grad=True)
b = torch.tensor([3.0,4.0], requires_grad=True)

y = w*x + b

In [46]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [47]:
# Tensor Initialization
data = [[1.0,2.0],[3.0,4.0]]
t1 = torch.tensor(data)
print(t1)

np_array = np.array(data)
t2 = torch.from_numpy(np_array)
print(t2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [48]:
x_ones = torch.ones_like(t1)
print(x_ones)

x_rand = torch.rand_like(t1)
print(x_rand)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.9452, 0.9802],
        [0.1347, 0.7298]])


In [49]:
shape=(2,3)
one_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)
rand_tensor = torch.rand(shape)
print(one_tensor)
print(zero_tensor)
print(rand_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1360, 0.4590, 0.2660],
        [0.4108, 0.1693, 0.9998]])


In [50]:
# Tensor Attributes
print(one_tensor.shape)   # shape of the tensor
print(one_tensor.dtype)   #  data type
print(one_tensor.device)  # device on which its stored

torch.Size([2, 3])
torch.float32
cpu


In [51]:
tensor = torch.ones(4,4)
print(tensor)
tensor[:,1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [52]:
# concatenating the tensors
t1 = torch.cat([tensor,tensor])
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [53]:
t1 = torch.cat([tensor,tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])


In [54]:
# Element wise multiplication
print(tensor.mul(tensor))
print(tensor*tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [55]:
# Matrix Multiplication of the tensors
print(tensor.matmul(tensor.T))
print(tensor @ tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [56]:
# In-place operations Operations that have a _ suffix are in-place. 
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [57]:
# tensor to numpy
tensor = torch.ones(5)
print(tensor)
t1 = tensor.numpy()
print(t1)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [58]:
# change in tensor, reflected in numpy
tensor.add_(3)
print(tensor)
print(t1)

tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


In [59]:
n = np.ones(5)
print(n)
t = torch.from_numpy(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [60]:
np.add(n,2,out=n)
print(n)
print(t)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


### Autograds

In [61]:
a = torch.tensor([1.0,2.0], requires_grad=True)
b = torch.tensor([3.0,4.0], requires_grad=True)

c = 3*a**2 + b**3
print(c)

tensor([30., 76.], grad_fn=<AddBackward0>)


In [62]:
c.sum().backward()

In [63]:
print(a.grad)
print(b.grad)

tensor([ 6., 12.])
tensor([27., 48.])


In [64]:
a = torch.tensor([1.0,2.0,3.0], requires_grad=True)
b = torch.tensor([4.0,5.0,6.0], requires_grad=True)

c = 3*a**2 + b**3
print(c)

tensor([ 67., 137., 243.], grad_fn=<AddBackward0>)


In [65]:
external_grad = torch.tensor([1., 1., 1.])
c.backward(gradient=external_grad)

In [66]:
print(a.grad)
print(b.grad)

tensor([ 6., 12., 18.])
tensor([ 48.,  75., 108.])


In [67]:
# The output tensor of an operation will require gradients even if only a single input tensor has requires_grad=True.

x = torch.rand(5, 5)
y = torch.rand(5, 5)
z = torch.rand((5, 5), requires_grad=True)

a = x + y
print(f"Does `a` require gradients? : {a.requires_grad}")
b = x + z
print(f"Does `b` require gradients?: {b.requires_grad}")

Does `a` require gradients? : False
Does `b` require gradients?: True
