In [1]:
import torch
import numpy as np

#### By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability).

In [6]:
tensor = torch.rand(3,4)
print(tensor)

tensor([[0.9085, 0.7310, 0.9703, 0.9859],
        [0.8757, 0.7319, 0.6833, 0.0125],
        [0.1252, 0.1245, 0.0555, 0.0995]])


In [7]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [8]:
print(f"First row: {tensor[0]}")

First row: tensor([0.9085, 0.7310, 0.9703, 0.9859])


In [9]:
print(f"First Column: {tensor[:,0]}")

First Column: tensor([0.9085, 0.8757, 0.1252])


In [10]:
print(f"Last Column:{tensor[:,-1]}")

Last Column:tensor([0.9859, 0.0125, 0.0995])


In [17]:
print(f"Last Column:{tensor[...,-1]}")

Last Column:tensor([0.9859, 0.0125, 0.0995])


In [19]:
tensor[:,1] = 0
print(tensor)

tensor([[0.9085, 0.0000, 0.9703, 0.9859],
        [0.8757, 0.0000, 0.6833, 0.0125],
        [0.1252, 0.0000, 0.0555, 0.0995]])


##### Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension

In [20]:
print(tensor)

tensor([[0.9085, 0.0000, 0.9703, 0.9859],
        [0.8757, 0.0000, 0.6833, 0.0125],
        [0.1252, 0.0000, 0.0555, 0.0995]])


In [22]:
t1 = torch.cat([tensor, tensor], dim=1)
print(t1)

tensor([[0.9085, 0.0000, 0.9703, 0.9859, 0.9085, 0.0000, 0.9703, 0.9859],
        [0.8757, 0.0000, 0.6833, 0.0125, 0.8757, 0.0000, 0.6833, 0.0125],
        [0.1252, 0.0000, 0.0555, 0.0995, 0.1252, 0.0000, 0.0555, 0.0995]])


In [23]:
t2 = torch.cat([tensor, tensor], dim=0)
print(t2)

tensor([[0.9085, 0.0000, 0.9703, 0.9859],
        [0.8757, 0.0000, 0.6833, 0.0125],
        [0.1252, 0.0000, 0.0555, 0.0995],
        [0.9085, 0.0000, 0.9703, 0.9859],
        [0.8757, 0.0000, 0.6833, 0.0125],
        [0.1252, 0.0000, 0.0555, 0.0995]])


In [24]:
t3 = torch.cat([tensor, tensor], dim=2)
print(t3)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [25]:
t4 = torch.cat([tensor, tensor], dim=-1)
print(t4)

tensor([[0.9085, 0.0000, 0.9703, 0.9859, 0.9085, 0.0000, 0.9703, 0.9859],
        [0.8757, 0.0000, 0.6833, 0.0125, 0.8757, 0.0000, 0.6833, 0.0125],
        [0.1252, 0.0000, 0.0555, 0.0995, 0.1252, 0.0000, 0.0555, 0.0995]])


In [26]:
t5 = torch.cat([tensor, tensor], dim=-2)
print(t5)

tensor([[0.9085, 0.0000, 0.9703, 0.9859],
        [0.8757, 0.0000, 0.6833, 0.0125],
        [0.1252, 0.0000, 0.0555, 0.0995],
        [0.9085, 0.0000, 0.9703, 0.9859],
        [0.8757, 0.0000, 0.6833, 0.0125],
        [0.1252, 0.0000, 0.0555, 0.0995]])


### Matrix Multiplication

In [28]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will 
# have the same value ``tensor.T`` returns the transpose of a tensor

y1 = tensor @ tensor.T 
print(f"y1: {y1}")

y2 = tensor.matmul(tensor.T)
print(f"y2:{y2}")

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(f"y3:{y3}")

y1: tensor([[2.7389, 1.4709, 0.2657],
        [1.4709, 1.2339, 0.1488],
        [0.2657, 0.1488, 0.0287]])
y2:tensor([[2.7389, 1.4709, 0.2657],
        [1.4709, 1.2339, 0.1488],
        [0.2657, 0.1488, 0.0287]])
y3:tensor([[2.7389, 1.4709, 0.2657],
        [1.4709, 1.2339, 0.1488],
        [0.2657, 0.1488, 0.0287]])


### Element Wise Multiplication

In [32]:
# This computes the element-wise product. z1, z2, z3 will have the same value

z1 = tensor * tensor
print(f"z1:{z1}")

z2 = tensor.mul(tensor)
print(f"z2:{z2}")

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(f"z3:{z3}")

z1:tensor([[8.2541e-01, 0.0000e+00, 9.4153e-01, 9.7194e-01],
        [7.6684e-01, 0.0000e+00, 4.6690e-01, 1.5652e-04],
        [1.5666e-02, 0.0000e+00, 3.0789e-03, 9.9102e-03]])
z2:tensor([[8.2541e-01, 0.0000e+00, 9.4153e-01, 9.7194e-01],
        [7.6684e-01, 0.0000e+00, 4.6690e-01, 1.5652e-04],
        [1.5666e-02, 0.0000e+00, 3.0789e-03, 9.9102e-03]])
z3:tensor([[8.2541e-01, 0.0000e+00, 9.4153e-01, 9.7194e-01],
        [7.6684e-01, 0.0000e+00, 4.6690e-01, 1.5652e-04],
        [1.5666e-02, 0.0000e+00, 3.0789e-03, 9.9102e-03]])


#### Single-element tensors 
##### If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [35]:
agg = tensor.sum()
print(f"agg:{agg}")

agg_item = agg.item()
print(f"agg_item:{agg_item}")
print(f"type(agg_item):{type(agg_item)}")

agg:4.716429233551025
agg_item:4.716429233551025
type(agg_item):<class 'float'>


#### In-place operations
##### Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

In [37]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[0.9085, 0.0000, 0.9703, 0.9859],
        [0.8757, 0.0000, 0.6833, 0.0125],
        [0.1252, 0.0000, 0.0555, 0.0995]])
tensor([[5.9085, 5.0000, 5.9703, 5.9859],
        [5.8757, 5.0000, 5.6833, 5.0125],
        [5.1252, 5.0000, 5.0555, 5.0995]])
