# Tensors

#### What are tensors ?
-   Tensors are a specialized data structure that are very similar to arrays and matrices
-   Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators.
-   Tensors are also optimized for automatic differentiation

In [ ]:
!pip3 install torch
!pip3 install numpy

In [9]:
import torch
import numpy as np

#### Initializing a Tensor

In [10]:
# Directly from data
data = [[1,2],[3,4]]
print(data)
x_data = torch.tensor(data)
print(x_data) 

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


In [11]:
# From numpy
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [12]:
# From another tensor
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.2464, 0.9438],
        [0.4221, 0.1215]])


In [13]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
print(rand_tensor)

ones_tensor = torch.ones(shape)
print(ones_tensor)

zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

tensor([[0.3208, 0.8134, 0.6730],
        [0.0099, 0.1365, 0.1323]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
rand_tensor = torch.rand(3,4)
print(rand_tensor)

tensor([[0.9987, 0.2572, 0.8173, 0.2361],
        [0.6294, 0.2333, 0.7074, 0.9823],
        [0.8410, 0.4442, 0.9161, 0.7198]])


In [16]:
print(f"shape of tensor {rand_tensor.shape}")
print(f"datatype of tensor {rand_tensor.dtype}")
print(f"Device tensor is stored on {rand_tensor.device}")

shape of tensor torch.Size([3, 4])
datatype of tensor torch.float32
Device tensor is stored on cpu
